import { FileJson, Upload } from 'lucide-react';
import { useCallback, useState } from 'react';
import { toast } from 'sonner';

import { cn } from '@common';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Textarea } from '@/components/ui/textarea';

interface ImportSectionProps {
	isLoaded: boolean;
	onImport: (json: string) => boolean;
}

export const ImportSection = ({ isLoaded, onImport }: ImportSectionProps) => {
	// 1. CLASSES OBJECT
	const classes = {
		importCardContent: cn('space-y-4'),
	};

	// 2. STATE
	const [jsonInput, setJsonInput] = useState('');

	// 3. CALLBACKS
	const handleImportFromTextarea = useCallback(() => {
		if (!jsonInput.trim()) {
			toast.error('Please paste the repository context JSON');
			return;
		}

		const success = onImport(jsonInput.trim());
		if (success) {
			setJsonInput('');
			toast.success('Repository context imported successfully');
		} else {
			toast.error('Failed to parse JSON. Make sure it was generated by the index-repo script.');
		}
	}, [jsonInput, onImport]);

	const handleImportFromFile = useCallback(
		(event: React.ChangeEvent<HTMLInputElement>) => {
			const file = event.target.files?.[0];
			if (!file) return;

			const reader = new FileReader();
			reader.onload = (e) => {
				const content = e.target?.result as string;
				const success = onImport(content);
				if (success) {
					toast.success('Repository context imported successfully');
				} else {
					toast.error('Failed to parse JSON file');
				}
			};
			reader.readAsText(file);
			event.target.value = '';
		},
		[onImport]
	);

	if (isLoaded) return null;

	// 4. RENDERS
	const renderInstructions = () => (
		<Alert className="mb-6">
			<FileJson className="h-4 w-4" />
			<AlertTitle>How to generate context</AlertTitle>
			<AlertDescription>
				Run the indexer script on your target repository:
				<pre className="mt-2 p-2 bg-muted rounded text-xs">
					node scripts/index-repo.mjs /path/to/your/repo ./repo-context.json
				</pre>
				Then import the generated JSON file here.
			</AlertDescription>
		</Alert>
	);

	return (
		<>
			{renderInstructions()}
			<Card className="mb-6">
				<CardHeader>
					<CardTitle>Import Repository Context</CardTitle>
					<CardDescription>
						Paste the JSON output from the index-repo script or upload the file
					</CardDescription>
				</CardHeader>
				<CardContent className={classes.importCardContent}>
					<Textarea
						value={jsonInput}
						onChange={(e) => setJsonInput(e.target.value)}
						placeholder='Paste your repo-context.json content here...\n\n{\n  "meta": { ... },\n  "summary": { ... },\n  "tree": { ... },\n  "compactTree": "..."\n}'
						className="min-h-[200px] font-mono text-xs"
					/>

					<div className="flex gap-2">
						<Button onClick={handleImportFromTextarea} disabled={!jsonInput.trim()}>
							Import from Text
						</Button>

						<label>
							<Button variant="outline" asChild>
								<span>
									<Upload className="h-4 w-4 mr-2" />
									Upload JSON File
									<input
										type="file"
										accept=".json"
										onChange={handleImportFromFile}
										className="sr-only"
									/>
								</span>
							</Button>
						</label>
					</div>
				</CardContent>
			</Card>
		</>
	);
};
