import type { RepositoryNode } from '@domain/repository';
import { useRepositoryStore } from '@domain/stores';
import {
	ChevronDown,
	ChevronRight,
	File,
	FileJson,
	Folder,
	FolderOpen,
	FolderTree,
	Trash2,
	Upload,
} from 'lucide-react';
import { useState } from 'react';
import { toast } from 'sonner';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Textarea } from '@/components/ui/textarea';

interface TreeNodeProps {
	node: RepositoryNode;
	level: number;
}

function TreeNode({ node, level }: TreeNodeProps) {
	const [isExpanded, setIsExpanded] = useState(level < 2);

	const isDirectory = node.type === 'directory';
	const hasChildren = isDirectory && node.children && node.children.length > 0;

	return (
		<div>
			{/* biome-ignore lint/a11y/noStaticElementInteractions: handled manually with role and keyboard listeners */}
			<div
				role={hasChildren ? 'button' : undefined}
				tabIndex={hasChildren ? 0 : undefined}
				className="flex items-center gap-1 py-0.5 px-2 hover:bg-muted/50 rounded cursor-pointer"
				style={{ paddingLeft: `${level * 16 + 8}px` }}
				onClick={() => hasChildren && setIsExpanded(!isExpanded)}
				onKeyDown={(e) => {
					if (hasChildren && (e.key === 'Enter' || e.key === ' ')) {
						e.preventDefault();
						setIsExpanded(!isExpanded);
					}
				}}
			>
				{hasChildren ? (
					isExpanded ? (
						<ChevronDown className="h-4 w-4 text-muted-foreground shrink-0" />
					) : (
						<ChevronRight className="h-4 w-4 text-muted-foreground shrink-0" />
					)
				) : (
					<span className="w-4" />
				)}

				{isDirectory ? (
					isExpanded ? (
						<FolderOpen className="h-4 w-4 text-amber-500 shrink-0" />
					) : (
						<Folder className="h-4 w-4 text-amber-500 shrink-0" />
					)
				) : (
					<File className="h-4 w-4 text-muted-foreground shrink-0" />
				)}

				<span className={`text-sm ${node.important ? 'font-medium' : ''}`}>{node.name}</span>

				{node.important && (
					<Badge variant="outline" className="text-xs ml-2 py-0">
						key file
					</Badge>
				)}
			</div>

			{isExpanded && hasChildren && (
				<div>
					{node.children
						?.sort((a, b) => {
							if (a.type !== b.type) return a.type === 'directory' ? -1 : 1;
							return a.name.localeCompare(b.name);
						})
						.map((child) => (
							<TreeNode key={child.path} node={child} level={level + 1} />
						))}
				</div>
			)}
		</div>
	);
}

export function ContextPage() {
	const { context, isLoaded, importFromJson, clearContext } = useRepositoryStore();
	const [jsonInput, setJsonInput] = useState('');

	const handleImportFromTextarea = () => {
		if (!jsonInput.trim()) {
			toast.error('Please paste the repository context JSON');
			return;
		}

		const success = importFromJson(jsonInput.trim());
		if (success) {
			setJsonInput('');
			toast.success('Repository context imported successfully');
		} else {
			toast.error('Failed to parse JSON. Make sure it was generated by the index-repo script.');
		}
	};

	const handleImportFromFile = (event: React.ChangeEvent<HTMLInputElement>) => {
		const file = event.target.files?.[0];
		if (!file) return;

		const reader = new FileReader();
		reader.onload = (e) => {
			const content = e.target?.result as string;
			const success = importFromJson(content);
			if (success) {
				toast.success('Repository context imported successfully');
			} else {
				toast.error('Failed to parse JSON file');
			}
		};
		reader.readAsText(file);
		event.target.value = '';
	};

	const handleClear = () => {
		clearContext();
		toast.success('Repository context cleared');
	};

	return (
		<div className="container mx-auto max-w-4xl py-8 px-4">
			<div className="flex items-center gap-3 mb-8">
				<FolderTree className="h-8 w-8 text-primary" />
				<div>
					<h1 className="text-3xl font-bold">Repository Context</h1>
					<p className="text-muted-foreground">
						Import your repository structure for context-aware tickets
					</p>
				</div>
			</div>

			{/* Instructions */}
			<Alert className="mb-6">
				<FileJson className="h-4 w-4" />
				<AlertTitle>How to generate context</AlertTitle>
				<AlertDescription>
					Run the indexer script on your target repository:
					<pre className="mt-2 p-2 bg-muted rounded text-xs">
						node scripts/index-repo.mjs /path/to/your/repo ./repo-context.json
					</pre>
					Then import the generated JSON file here.
				</AlertDescription>
			</Alert>

			{/* Import Section */}
			{!isLoaded && (
				<Card className="mb-6">
					<CardHeader>
						<CardTitle>Import Repository Context</CardTitle>
						<CardDescription>
							Paste the JSON output from the index-repo script or upload the file
						</CardDescription>
					</CardHeader>
					<CardContent className="space-y-4">
						<Textarea
							value={jsonInput}
							onChange={(e) => setJsonInput(e.target.value)}
							placeholder='Paste your repo-context.json content here...\n\n{\n  "meta": { ... },\n  "summary": { ... },\n  "tree": { ... },\n  "compactTree": "..."\n}'
							className="min-h-[200px] font-mono text-xs"
						/>

						<div className="flex gap-2">
							<Button onClick={handleImportFromTextarea} disabled={!jsonInput.trim()}>
								Import from Text
							</Button>

							<label>
								<Button variant="outline" asChild>
									<span>
										<Upload className="h-4 w-4 mr-2" />
										Upload JSON File
										<input
											type="file"
											accept=".json"
											onChange={handleImportFromFile}
											className="sr-only"
										/>
									</span>
								</Button>
							</label>
						</div>
					</CardContent>
				</Card>
			)}

			{/* Loaded Context Display */}
			{isLoaded && context && (
				<div className="space-y-6">
					{/* Summary Card */}
					<Card>
						<CardHeader>
							<div className="flex items-center justify-between">
								<div>
									<CardTitle>{context.meta.repositoryName}</CardTitle>
									<CardDescription>
										Indexed on {new Date(context.meta.generatedAt).toLocaleString()}
									</CardDescription>
								</div>
								<Button variant="outline" onClick={handleClear}>
									<Trash2 className="h-4 w-4 mr-2" />
									Clear
								</Button>
							</div>
						</CardHeader>
						<CardContent>
							<div className="grid grid-cols-2 md:grid-cols-4 gap-4">
								<div className="text-center p-4 bg-muted rounded-lg">
									<div className="text-2xl font-bold">{context.summary.totalFiles}</div>
									<div className="text-sm text-muted-foreground">Files</div>
								</div>
								<div className="text-center p-4 bg-muted rounded-lg">
									<div className="text-2xl font-bold">{context.summary.totalDirectories}</div>
									<div className="text-sm text-muted-foreground">Directories</div>
								</div>
								<div className="text-center p-4 bg-muted rounded-lg">
									<div className="text-2xl font-bold">{context.summary.importantPaths.length}</div>
									<div className="text-sm text-muted-foreground">Key Files</div>
								</div>
								<div className="text-center p-4 bg-muted rounded-lg">
									<div className="text-2xl font-bold">
										{Object.keys(context.summary.filesByExtension).length}
									</div>
									<div className="text-sm text-muted-foreground">File Types</div>
								</div>
							</div>

							{/* File Types */}
							<div className="mt-4">
								<h4 className="font-medium mb-2">File Types</h4>
								<div className="flex flex-wrap gap-2">
									{Object.entries(context.summary.filesByExtension)
										.sort((a, b) => b[1] - a[1])
										.slice(0, 10)
										.map(([ext, count]) => (
											<Badge key={ext} variant="secondary">
												{ext}: {count}
											</Badge>
										))}
								</div>
							</div>
						</CardContent>
					</Card>

					{/* Tree View */}
					<Card>
						<CardHeader>
							<CardTitle>Repository Structure</CardTitle>
							<CardDescription>Click folders to expand/collapse</CardDescription>
						</CardHeader>
						<CardContent>
							<ScrollArea className="h-[400px] border rounded-lg">
								<div className="py-2">
									<TreeNode node={context.tree} level={0} />
								</div>
							</ScrollArea>
						</CardContent>
					</Card>
				</div>
			)}
		</div>
	);
}
